version: '3'

services:
  redis:
    image: redis:latest 
    container_name: redis_container
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data
    



  db:
    image: postgres
    container_name: database_container
    environment:
      POSTGRES_DB: coloshop
      POSTGRES_USER: muhammedarfath
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data




  django_app:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    container_name: shop_container
    volumes:
      - static_vol:/mysite/home/static
      - media_vol:/mysite/home/media
    ports:
      - "8000:8000"
    depends_on:
      - db
 

  nginx:
    build: ./nginx
    volumes:
      - static_vol:/mysite/home/static
      - media_vol:/mysite/home/media
    ports:
      - "80:80"
    depends_on:
      - django_app



volumes:
  postgres_data:
  redis_data:
  media_vol:
  static_vol:


