# Generated by Django 4.2.6 on 2023-11-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_color_size_product_variant_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
