# Generated by Django 4.2.6 on 2023-11-16 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
    ]
