# Generated by Django 4.2.6 on 2023-11-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
