# Generated by Django 4.2.6 on 2023-11-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_imagetypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetypes',
            name='product',
        ),
    ]
