# Generated by Django 4.2.6 on 2023-11-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_imagetypes_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetypes',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variants'),
        ),
    ]
