# Generated by Django 4.2.6 on 2023-11-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_imagetypes_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetypes',
            name='variant',
        ),
    ]
