# Generated by Django 4.2.6 on 2023-11-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_imagetypes_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='image_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.imagetypes'),
        ),
    ]
