# Generated by Django 4.2.6 on 2023-11-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_variants_image_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='image_types',
        ),
        migrations.AddField(
            model_name='variants',
            name='image_types',
            field=models.ManyToManyField(blank=True, null=True, to='product.imagetypes'),
        ),
    ]
