# Generated by Django 4.2.6 on 2023-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_variants_image_types_variants_image_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='image_types',
            field=models.ManyToManyField(blank=True, to='product.imagetypes'),
        ),
    ]
