# Generated by Django 4.2.6 on 2023-11-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_variants_image_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetypes',
            name='image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
