# Generated by Django 4.2.6 on 2023-11-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
