# Generated by Django 4.2.6 on 2023-11-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_alter_coupon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
