# Generated by Django 4.2.6 on 2023-12-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0011_remove_coupon_one_time_use_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_one_time_use',
            field=models.BooleanField(default=False),
        ),
    ]
