# Generated by Django 4.2.6 on 2023-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_wishlist_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='variant',
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
