# Generated by Django 4.2.6 on 2023-11-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_wishlistitem_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/'),
        ),
    ]
