# Generated by Django 4.2.6 on 2023-11-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_imagetypes_image_id'),
        ('user', '0007_userprofile_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.variants'),
        ),
    ]
