# Generated by Django 4.2.6 on 2023-12-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0012_coupon_is_one_time_use'),
        ('user', '0014_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon'),
        ),
    ]
