# Generated by Django 4.2.6 on 2023-10-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartview'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='cart_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cartview'),
        ),
    ]
