# Generated by Django 4.2.6 on 2023-11-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_shopcart_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
