# Generated by Django 4.2.6 on 2023-11-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='state',
        ),
    ]
