# Generated by Django 4.2.6 on 2023-11-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_tracking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
