# Generated by Django 4.2.6 on 2023-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_code_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.FloatField(default=None),
        ),
    ]
