# Generated by Django 4.2.6 on 2023-11-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='product',
        ),
    ]
