# Generated by Django 4.2.6 on 2023-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_rename_address_order_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
