# Generated by Django 4.2.6 on 2023-11-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
