# Generated by Django 4.2.6 on 2023-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_order_first_name_alter_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
