# Generated by Django 4.2.6 on 2023-11-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
