# Generated by Django 4.2.6 on 2023-11-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_remove_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'New'), (1, 'Accepted'), (2, 'Preaparing'), (3, 'OnShipping'), (4, 'Completed'), (5, 'Canceled')], default='New', max_length=10),
        ),
    ]
