# Generated by Django 4.2.6 on 2023-11-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'New'), (2, 'Accepted'), (3, 'Preparing'), (4, 'OnShipping'), (5, 'Completed'), (6, 'Canceled')], default=1, null=True),
        ),
    ]
