# Generated by Django 4.2.6 on 2023-12-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_alter_order_address_line1_alter_order_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
