# Generated by Django 4.2.6 on 2023-12-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_order_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_status',
            new_name='user_product_status',
        ),
    ]
