# Generated by Django 4.2.6 on 2023-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_orderproduct_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Return', 'Return'), ('Canceled', 'Canceled')], default='New', max_length=10),
        ),
    ]
